bingoSpaces = [
"\"I have been a TaxAct customer for ____ years\"",
"McAfee or other antivirus",
"Threatening to switch to another company",
"\"I have a client waiting\"",
"Republic Bank issue",
"Other company blames us",
"\"Can you hear me\"",
"Driving/Not in front of PC when calling",
"Arguing about being transferred",
"\"Can I speak to a supervisor\"",
"\"Do you have someone a speak spanish\"",
"\"I'm not tech savvy\"",
"Asking \"How are you\" then not letting you answer",
"Arguing/not following instructions given to them",
"\"Walk me through it\"",
"Glitch/Bug with the program",
"\"This has never happened before\"",
"Asking for Efile status after less than 24 hours",
"\"When will form ___ be available\"",
"Asking for a discount",
"Using a Mac",
"Consumer on Pro line",
"Threatening legal action/BBB",
"Wanting instant EFIN verifcation",
"Swearing or Yelling",
"Rambling on repeating them selves about something useless",
"EFIN never verified",
"Place an order",
"Refund",
"Enterprise switch",
"LAN setup issues",
"Struggling to upload correct efin doc",
"Compares us to another company",
"Verification code issues",
"\"This is unacceptable\"",
"On website instead of program",
"CIT User",
"80 + year old caller",
"Celebrity Caller",
"Customer Interrupts",
"\"I'm not a professional but....\"",
"\"Im not going to recommend you any more\"",
"\"This is my ___ time calling...\"",
"\"Do you have someone who can help you?\"",
"Calling Basic windows features a bug"
]